[package]
name = "hill-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.2"
bevy_console = "0.13.1"
bevy_lunex = "0.3.2"
clap = "4.5.31"
serde = "1.0.218"
serde_json = "1.0.139"
